name: bible_bot
description: bible_bot

version: 2.0.4+36

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  # https://pub.dev/packages/url_launcher#-r eadme-tab-
  url_launcher: ^5.4.2

  # https://pub.dev/packages/package_info
  package_info: ^0.4.0+16

  # https://pub.dev/packages/flushbar
  flushbar: ^1.10.4

  # https://pub.dev/packages/sliding_up_panel#-installing-tab-
  sliding_up_panel: ^1.0.0

  # https://pub.dev/packages/photo_view
  photo_view: ^0.9.1

  flutter:
    sdk: flutter

  # https://pub.dev/packages/flutter_swiper#-installing-tab-
  flutter_swiper: ^1.1.6

  # https://pub.dev/packages/percent_indicator#-installing-tab-
  percent_indicator: ^2.1.1+1

  # https://pub.dev/packages/test#-installing-tab-
  test: ^1.9.4

  # https://pub.dev/packages/http#-installing-tab-
  http: ^0.12.0+2

  # https://pub.dev/packages/shared_preferences#-readme-tab-
  shared_preferences: ^0.5.6

  # https://pub.dev/packages/provider#-installing-tab-
  provider: ^3.2.0

  # https://pub.dev/packages/intl
  intl: ^0.16.0

  # https://pub.dev/packages/table_calendar
  table_calendar: ^2.2.2

  # https://pub.dev/packages/flutter_webview_plugin#-installing-tab-
  flutter_webview_plugin: ^0.3.10+1

  # https://pub.dev/packages/flutter_cupertino_date_picker
  flutter_cupertino_date_picker: ^1.0.26

  # https://pub.dev/packages/cupertino_icons
  cupertino_icons: ^0.1.2

  # https://pub.dev/packages/jiffy
  jiffy: ^3.0.1

  # https://pub.dev/packages/syncfusion_flutter_calendar
  syncfusion_flutter_calendar: ^18.1.44-beta

  # https://pub.dev/packages/syncfusion_flutter_core
  syncfusion_flutter_core: ^18.1.44

  # https://pub.dev/packages/date_range_picker
  date_range_picker: ^1.0.6

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # http://company.lottemart.com/bc/service/htmlView.do?menuCd=BM0307&SITELOC=DB005

  uses-material-design: true

  assets:
    - images/
    - licenses/
